/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef PdfConverter_CONSTANTS_H
#define PdfConverter_CONSTANTS_H

#include "PdfConverter_types.h"



class PdfConverterConstants {
 public:
  PdfConverterConstants();

  std::string FILE_BASE_PATH;
};

extern const PdfConverterConstants g_PdfConverter_constants;



#endif
