/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "PdfConverter_constants.h"



const PdfConverterConstants g_PdfConverter_constants;

PdfConverterConstants::PdfConverterConstants() {
  FILE_BASE_PATH = "/data/htmls";

}



