/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef PdfConverter_TYPES_H
#define PdfConverter_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





typedef struct _PdfJob__isset {
  _PdfJob__isset() : pdfFile(false), id(false) {}
  bool pdfFile;
  bool id;
} _PdfJob__isset;

class PdfJob {
 public:

  static const char* ascii_fingerprint; // = "1CCCF6FC31CFD1D61BBBB1BAF3590620";
  static const uint8_t binary_fingerprint[16]; // = {0x1C,0xCC,0xF6,0xFC,0x31,0xCF,0xD1,0xD6,0x1B,0xBB,0xB1,0xBA,0xF3,0x59,0x06,0x20};

  PdfJob() : pdfFile(""), id(0) {
  }

  virtual ~PdfJob() throw() {}

  std::string pdfFile;
  int64_t id;

  _PdfJob__isset __isset;

  bool operator == (const PdfJob & rhs) const
  {
    if (!(pdfFile == rhs.pdfFile))
      return false;
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const PdfJob &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PdfJob & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PdfJobResult__isset {
  _PdfJobResult__isset() : isSuccess(false), pageCount(false) {}
  bool isSuccess;
  bool pageCount;
} _PdfJobResult__isset;

class PdfJobResult {
 public:

  static const char* ascii_fingerprint; // = "88440F45A63E63607868B983E4E50558";
  static const uint8_t binary_fingerprint[16]; // = {0x88,0x44,0x0F,0x45,0xA6,0x3E,0x63,0x60,0x78,0x68,0xB9,0x83,0xE4,0xE5,0x05,0x58};

  PdfJobResult() : isSuccess(0), pageCount(0) {
  }

  virtual ~PdfJobResult() throw() {}

  bool isSuccess;
  int32_t pageCount;

  _PdfJobResult__isset __isset;

  bool operator == (const PdfJobResult & rhs) const
  {
    if (!(isSuccess == rhs.isSuccess))
      return false;
    if (!(pageCount == rhs.pageCount))
      return false;
    return true;
  }
  bool operator != (const PdfJobResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PdfJobResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
